@startuml

interface ReprodutorMusical {
    +void tocar()
    +void pausar()
    +void selecionarMusica()
}

interface AparelhoTelefonico {
    +void ligar()
    +void atender()
    +void iniciarCorreioVoz()
}

interface NavegadorInternet {
    +void exibirPagina()
    +void adicionarNovaAba()
    +void atualizarPagina()
}

class IPhone implements ReprodutorMusical, AparelhoTelefonico, NavegadorInternet {
    +void ligar()
    +void atender()
    +void iniciarCorreioVoz()
    +void exibirPagina()
    +void adicionarNovaAba()
    +void atualizarPagina()
    +void tocar()
    +void pausar()
    +void selecionarMusica()
}

@enduml
